controllers/CommentsController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\Comments;
use app\models\CommentsSearch;

class CommentsController extends Controller
{
    public $model;
    public $modelSearch;
    
    public function __construct($id, $module, $config = array()) {
        $this->model = new Comments();
        $this->modelSearch = new CommentsSearch();
        parent::__construct($id, $module, $config);
    } 
    
    public function actionCreate()
    {
        if ($this->model->load(Yii::$app->request->post())) {
            $this->model->save();
            return $this->redirect(['index']);
        }
        
        return $this->render('create', [
            'model' => $this->model
        ]);
    }
    
    public function actionSubmit()
    {
        if ($this->model->load(Yii::$app->request->post())) {
            if($model->validate())
            {
                $this->model->save();
            }
            return $this->redirect(['index']);
        }
    }

    public function actionIndex()
    {
        $dataProvider = $this->modelSearch->search(Yii::$app->request->get());
        
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $this->modelSearch,
        ]);
    }

    public function actionDelete($id)
    {
        Comments::findOne($id)->delete();
        return $this->redirect(['index']);
    }

    public function actionSearch()
    {
        return $this->render('search');
    }

    public function actionUpdate($id)
    {
        $model = Comments::findOne($id);
        if ($model->load(Yii::$app->request->post())) {
            $model->save();
            return $this->redirect(['index']);
        }
        else{
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionView($id)
    {
        return $this->render('view', [
            'model' => Comments::findOne($id),
        ]);
    }

}

controllers/CoverController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\Cover;
use app\models\CoverSearch;
use yii\web\UploadedFile;

class CoverController extends Controller
{
    public $model;
    public $modelSearch;
    
    public function __construct($id, $module, $config = array()) {
        $this->model = new Cover();
        $this->modelSearch = new CoverSearch();
        parent::__construct($id, $module, $config);
    } 
    
    public function actionIndex()
    {
        $dataProvider = $this->modelSearch->search(Yii::$app->request->get());
        
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $this->modelSearch,
        ]);
    }
    
    public function actionCreate()
    {
        if ($this->model->load(Yii::$app->request->post())) {
            //get the instance of the image
            $image = UploadedFile::getInstance($this->model, 'image_link');
            //get the image name
            $this->model->image_link = 'assets/images/'.$image->baseName.'.'.$image->extension;
            //validate the save before uploading the image
            if($this->model->save()){
                $image->saveAs($this->model->image_link);
            }

            return $this->redirect(['index']);
        }
        
        return $this->render('create', [
            'model' => $this->model
        ]);
    }

    public function actionDelete($id)
    {
        Cover::findOne($id)->delete();
        return $this->redirect(['index']);
    }

    public function actionSearch()
    {
        return $this->render('search');
    }

    public function actionUpdate($id)
    {
        $model = Cover::findOne($id);
        if ($model->load(Yii::$app->request->post())) {
            $model->save();
            return $this->redirect(['index']);
        }
        else{
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionView($id)
    {
        return $this->render('view', [
            'model' => Cover::findOne($id),
        ]);
    }
    
    public function upload()
    {
        $this->model->image_link = Cover::getInstance($this->model, 'imageFile');
        if ($this->validate()) {
            $this->upload();
            $this->model->image_link->saveAs('assets/images/' . $this->model->image_link->baseName . '.' . $this->model->image_link->extension);
            return true;
        } else {
            return false;
        }
    }
}

controllers/GameController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\Game;
use app\models\GameSearch;
use yii\web\UploadedFile;

class GameController extends Controller
{
    public $model;
    public $modelSearch;
    
    public function __construct($id, $module, $config = array()) {
        $this->model = new Game();
        $this->modelSearch = new GameSearch();
        parent::__construct($id, $module, $config);
    }      
    
    public function actionCreate()
    {
        
        if ($this->model->load(Yii::$app->request->post())) {
            //get the last ID of the table, the last ID is generated on create
            $last_id = $this->model->getLastID();
            $this->model->id = $last_id[0]['last_id'];
            //randomize the url
            $this->model->url = 'index.php?r=site%2Fdetail&id='.$last_id[0]['last_id'];
            //get the instance of the image
            $image = UploadedFile::getInstance($this->model, 'image_link');
            //get the image name
            $this->model->image_link = 'assets/images/'.$image->baseName.'.'.$image->extension;
            //validate the save before uploading the image
            if($this->model->save()){
                $image->saveAs($this->model->image_link);
                return self::actionIndex();
            }
        }
        
        return $this->render('create', [
            'model' => $this->model
        ]);
    }

    public function actionIndex()
    {
        $dataProvider = $this->modelSearch->search(Yii::$app->request->get());
        
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $this->modelSearch,
        ]);
    }

    public function actionDelete($id)
    {
        $this->model->findOne($id)->delete();
        return $this->redirect(['index']);
    }

    public function actionSearch()
    {
        return $this->render('search');
    }

    public function actionUpdate($id)
    {
        $model = $this->model->findOne($id);
        if ($model->load(Yii::$app->request->post())) {
            $model->save();
            return $this->redirect(['index']);
        }
        else{
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->model->findOne($id),
        ]);
    }

}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => '<img src="assets/images/logo.png" class="logo img-responsive"/>',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            !Yii::$app->user->isGuest ? ['label' => 'Cover', 'url' => ['/cover/index']] : '',
            !Yii::$app->user->isGuest ? ['label' => 'Game', 'url' => ['/game/index']] : '',
            !Yii::$app->user->isGuest ? ['label' => 'Comments', 'url' => ['/comments/index']] : '',
            Yii::$app->user->isGuest ? 
                ['label' => 'Login', 'url' => ['/site/login']]
             : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ]
    ]);
    NavBar::end();
    ?>
    
    <div class="container">
        <?= $content ?>
    </div>
</div>



<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>