controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Users;
use app\models\Cover;
use app\models\CoverSearch;
use app\models\Game;
use app\models\Comments;
use yii\data\ActiveDataProvider;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }
    
    public $usersModel;
    public $coverModel;
    public $commentsModel;
    public $gameModel;
    
    public function __construct($id, $module, $config = array()) {
        $this->usersModel = new Users();
        $this->coverModel = new Cover();
        $this->commentsModel = new Comments();
        $this->gameModel = new Game();
        parent::__construct($id, $module, $config);
    } 

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $covers = Cover::find()->all();
        $games = Game::find()->all();
        return $this->render('index', [
            'covers' => $covers,
            'games' => $games,
        ]);
    }
    
    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionDetail($id)
    {
        if ($this->commentsModel->load(Yii::$app->request->post())) {
                $this->commentsModel->setDate();
                $this->commentsModel->save();
                return $this->redirect(['site/detail', 'id' =>$id]);
        }
        
        $result = Game::findOne($id);
        $comments = Comments::find()->where(['game_id' => $id])->all();
        foreach($result as $row => $item){
            $game[$row] = $item;
        }
        //die(print_r($game));
        return $this->render('detail', [
            'game' => $game,
            'comments' => $comments,
            'commentModel' => $this->commentsModel,
            'gameModel' => $this->gameModel,
            'usersModel' => $this->usersModel
        ]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }
    
    /**
     * Register action.
     *
     * @return Response|string
     */
    public function actionRegister()
    {
        
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        if ($this->usersModel->load(Yii::$app->request->post())) {
            $this->usersModel->setPassword($this->usersModel->password);
            $this->usersModel->setDatecreated();
            $this->usersModel->generateAuthKey();
            if($this->usersModel->validate())
            {
                $this->usersModel->save();
                \Yii::$app->session->setFlash('success',"You have signed up successfully. To have more fun, proceed by logging-in");
                return $this->redirect(['site/login']);
            }
        }
        return $this->render('register', [
            'model' => $this->usersModel,
        ]);
    }
    
    

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/detail.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\Detail */
/* @var $model app\models\Game */

$this->title = $game['title'];
$this->params['breadcrumbs'][] = ['label' => 'Game', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="form-container">
    <div class="row">
        <div class="col-lg-2">
            <div class="game-title"><h3><?= Html::encode($this->title) ?></h3></div>
        </div>
    </div>
                       
    <div class="row">
        <div class="col-lg-6">
            <img class="game-image" src="<?= $game['image_link']; ?>"/>
        </div>
        <div class="col-lg-6">
            <h3 class="title">Description</h3>
            <p class="game-description"><?= $game['description']; ?></p>
            <h3 class="title">Genre</h3>
            <p class="game-genre"><?= $game['genre']; ?></p>
        </div>
    </div>
    
    <div class="row">
        <div class="col-lg-6">
            <?php $comments = isset($comments) ? $comments : 0; ?>
            <h3><?php echo count($comments); ?> Comments</h3>
            <?php if($comments != 0){ ?>
            <?php foreach ($comments as $comment => $item): ?>
            <div class="row">
                <div class="col-lg-12">
                    <div class="comment-head">
                        <div class="col-lg-3">
                            <p class="title"><?= $usersModel->getUsernameById($item->created_by) ?></p>
                        </div>
                        <div class="col-lg-3">
                            <p class="title time"><?= $gameModel->time_ago($item->date_created) ?></p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="comment-body">
                        <p class="comment"><?= $item->comment ?></p>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
            <?php if(!Yii::$app->user->isGuest) { ?>
            <div class="form">
            <?php 
                        $form = ActiveForm::begin([
                                    'id' => 'comment-form',
                                    'layout' => 'horizontal',
                                    'fieldConfig' => [
                                        'template' => "{label}\n<div class=\"col-lg-6\">{input}</div>\n<div class=\"col-lg-3\">{error}</div>",
                                        'labelOptions' => ['class' => 'col-lg-3 control-label'],
                                    ],
                        ]);
                        ?>
            <?= Html::hiddenInput("Comments[game_id]", $game['id']); ?>
            <?= Html::hiddenInput("Comments[created_by]", Yii::$app->user->identity->id_user); ?>
            <?= $form->field($commentModel, 'comment')->textInput(['class' => 'string', 'size' => 50, 'placeholder' => 'Add Your Comment Here']) ?>
            <?= Html::submitButton('Submit', ['class' => 'sumbit', 'name' => 'comment-button']) ?>
            <?php ActiveForm::end(); ?>
            <?php } else { ?>
                <?= Html::a('Login to comment', ['site/login'], ['class' => 'btn btn-danger']) ?>
            <?php } ?>
            </div>
            <?php } ?>
        </div>
    </div>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">


    <div class="jumbotron">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                <?php $covers = isset($covers) ? $covers : array(); ?>
                <?php if (!empty($covers)) { ?>
                    <?php foreach ($covers as $cover => $item): ?>
                        <?php if ($cover === 0) { ?> <div class="item active"> 
                        <?php } else { ?> <div class="item"> <?php } ?>
                            <img src="<?= $item->image_link ?>" alt="Chania">
                                <div class="carousel-caption">
                                    <h3 class="title"><?php echo $item->caption; ?></h3>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    <?php }else { ?>
                        <div class="item active">
                            <img src="assets/images/empty.jpg" alt="Chania">
                            <div class="carousel-caption">
                                <h3 class="title">No Image, please add through the cover module !</h3>
                            </div>
                        <?php } ?>
                    </div>

                    <!-- Left and right controls -->
                    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" href="#myCarousel" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
        </div>
            <div class="body-content">
                <?php $games = isset($games) ? $games : array(); ?>
                <?php if (!empty($games)) { 
                        $limit = count($games); $x=0; $row=0; foreach ($games as $game => $item): 
                        if ($x % 3 === 0) { $row = $row +1; ?> <div class="row"> <?php } ?>
                        <div class="col-sm-4 col-md-4 box col-lg-4 box">
                                <span class="box-title">User Reviews</span>
                                <div class="box-pic">
                                    <a href="<?= $item->url ?>"><img src="<?= $item->image_link ?>" /></a>
                                </div>
                                <p class="caption"><?php echo $item->caption; ?><p>
                            </div>
                        <?php if (($x == $limit) || ($x == ((3*$row)-1))){ ?> </div> <?php } ?>
                        <?php $x++; endforeach; ?>
                            <?php }else { ?>
                        <div class="row"><div class="col-sm-4 col-md-4 box col-lg-4 box">
                            <span class="box-title">User Reviews</span>
                                <div class="box-pic">
                                    <img src="assets/images/box_empty.jpg" />
                                </div>
                                <p class="caption">No games yet, add through the game module !<p>
                                    </div></div>
                        <?php } ?>
            </div>
        </div>

views/site/login.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">

  <link rel='stylesheet prefetch' href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900'>
<link rel='stylesheet prefetch' href='https://fonts.googleapis.com/css?family=Montserrat:400,700'>
<link rel='stylesheet prefetch' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'>
<link rel="stylesheet" href="css/style.css">
<div class="site-login">
    <div class="form">
        <?php if(Yii::$app->session->hasFlash('success')){ ?>
        <div class="alert alert-success">
            <?php echo Yii::$app->session->getFlash('success'); ?>
        </div>
        <?php } ?>
        <?php
                        $form = ActiveForm::begin([
                                    'id' => 'login-form',
                                    'layout' => 'horizontal',
                                    'fieldConfig' => [
                                        'template' => "{label}\n<div class=\"col-sm-12 col-lg-12\">{input}</div>\n<div class=\"col-sm-12  col-lg-12\">{error}</div>",
                                        'labelOptions' => ['class' => 'col-sm-12 col-lg-12 control-label'],
                                    ]
                        ]);
                        ?>
          <?= $form->field($model, 'username')->textInput(['autofocus' => true, 'class' => 'string optional', 'size' => 50, 'placeholder' => 'Username']) ?>
          <?= $form->field($model, 'password')->passwordInput(['class' => 'string optional', 'placeholder' => 'Password', 'size' => 50, 'id' => 'user-pw']) ?>
          <?= Html::submitButton('Login', ['class' => 'sumbit', 'name' => 'login-button']) ?>
          <p class="message">Not registered? <?= Html::a('Create an account', ['/site/register']) ?></p>
        <?php ActiveForm::end(); ?>
      </div>
</div>

</div>
<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script  src="js/index.js"></script>

views/site/register.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">

  <link rel='stylesheet prefetch' href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900'>
<link rel='stylesheet prefetch' href='https://fonts.googleapis.com/css?family=Montserrat:400,700'>
<link rel='stylesheet prefetch' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'>
<link rel="stylesheet" href="css/style.css">

<div class="site-login">
    <div class="form">
        <?php
                        $form = ActiveForm::begin([
                                    'id' => 'register-form',
                                    'layout' => 'horizontal',
                                    'fieldConfig' => [
                                        'template' => "{label}\n<div class=\"col-sm-12 col-lg-6\">{input}</div>\n<div class=\"col-sm-12 col-lg-3\">{error}</div>",
                                        'labelOptions' => ['class' => 'col-sm-12 col-lg-3 control-label'],
                                    ]
                        ]);
                        ?>
          <?= $form->field($model, 'first_name')->textInput(['autofocus' => true, 'class' => 'string', 'size' => 50, 'placeholder' => 'Your First Name']) ?>
          <?= $form->field($model, 'last_name')->textInput(['class' => 'string', 'size' => 50, 'placeholder' => 'Your Last Name']) ?>
          <?= $form->field($model, 'email')->textInput(['type' => 'email', 'class' => 'string', 'size' => 50, 'placeholder' => 'Email Address']) ?>
          <?= $form->field($model, 'username')->textInput(['class' => 'string', 'size' => 50, 'placeholder' => 'Username']) ?>
          <?= $form->field($model, 'password')->passwordInput(['class' => 'string', 'placeholder' => 'Password', 'size' => 50, 'id' => 'user-pw']) ?>
                                <?= Html::submitButton('Register', ['class' => 'sumbit', 'name' => 'register-button']) ?>
          <p class="message">Already registered? <?= Html::a('Log In', ['/site/login2']) ?></p>
        <?php ActiveForm::end(); ?>
      </div>
</div>
<script  src="assets/index.js"></script>